### ISSUE TITLE
Port to 1.16.2/1.16.3/1.16.4

### ISSUE THREAD

**Issue by xbony2** [xbony2/Long-Fall-Boots#10]
I know, 1.16.1->1.16.2. But for some reason, specifying a license in the mod toml is now required, or was required but may be in the future. I don't know, Forge is wildin'.

**Comment by joehayden-code** [comment]
Added this mod to my download of Valhelsia 3 mod pack running Minecraft 1.16.3.  I added license="MIT" to the mod.toml file and it's working without any issues for me.  Unsure if that's the license you intend to use, but that seems to do the trick.

**Comment by xbony2** [comment]
Currently unlicensed although do what you want with it :P (I talked to the original creator yesterday and we will relicense to a FOSS license soon (tm) )
