### ISSUE TITLE
Keeps crashing my 1.19.2 pack

### ISSUE THREAD

**Issue by vizthex123** [xbony2/Long-Fall-Boots#14]
Here's the log:
[latest.log](https://github.com/xbony2/Long-Fall-Boots/files/9760155/latest.log)

No clue what's causing it, but the game works fine when I disable this mod.

**Comment by xbony2** [comment]
Thanks for this. 1.19.1 -> 1.19.2 broke another one of my mods but I assumed it would be fine for this one. It was not. I'll try to make a new version for 1.19.2 soon, and latest is now marked as 1.19/1.19.1 only.

**Comment by vizthex123** [comment]
noice, thanks

**Comment by xbony2** [comment]
@vizthex123 thanks for this. Let me know if it's still an issue. (1.9.1a should be CF approved shortly)

**Comment by vizthex123** [comment]
Works now, thanks for fixing it.
