### ISSUE TITLE
1.1-1.11 crashes dedicated server Forge 1.11.2 build 2516

### ISSUE THREAD

**Issue by kreezxil** [xbony2/Long-Fall-Boots#2]
Notes:
     on startup while looking for client side classes

crash report:
https://gist.github.com/b8880fa339369334dfb945a87c4502b1

fml server latest:
https://gist.github.com/e818723e48e83a3040e63eb219d6b78a

**Comment by xbony2** [comment]
That version isn't support by me I'm afraid. This repo is only for 1.12+.

**Comment by kreezxil** [comment]
On curse you have it tagged for 1.11.2

**Comment by xbony2** [comment]
Yes, that version is for 1.11/1.11.2. But that version isn't supported by me.

**Comment by kreezxil** [comment]
Weird because the issue link went to you.

Ok. Noted.

**Comment by xbony2** [comment]
There's not a repo or issue track for 1.11 so yeah.

**Comment by kreezxil** [comment]
this is getting tiresome.

https://minecraft.curseforge.com/projects/long-fall-boots

by nanoheart

I guess he forked your stuff then set his issue tracker to your page instead of his own

**Comment by kreezxil** [comment]
and looks like they added you as a maintainer to the original project.

Well, i'm done.

See you in 1.12 for my next great pack.
