### ISSUE TITLE
1.2.1b shows wrong version (shows 1.2.1a)

### ISSUE THREAD

**Issue by Laike-Endaril** [xbony2/Long-Fall-Boots#3]
Title says it all, not a major bug.  Probably just forgot to change version in build file.

**Comment by xbony2** [comment]
Well, I fixed it, although if I was to release another version from this then I would have to change the version number again :P

**Comment by Laike-Endaril** [comment]
Yeah, probably not worth a release on its own.
Now that I think about it, this mod seems fairly complete, so it may never see the light of day XD

Great mod btw; works well combined with other mods without being overpowered; even the default recipe is well balanced (at least in my pack).  I've disabled slime boots in my pack for several reasons and these boots are filling that role nicely (without the somewhat OP travelling speed of slime boots)
