### ISSUE TITLE
Still Taking Damage

### ISSUE THREAD

**Issue by masterschief** [xbony2/Long-Fall-Boots#8]
Hey, I'm running a modpack with the longfall boots mod and I'm still receiving fall damage when wearing them. Is there anything this mod would conflict with? I've run a singleplayer world just to test and the boots work just fine there, but on the server I take normal fall damage.

**Comment by masterschief** [comment]
Update: I've realized that OTG generation, specifically using Biome Bundle will negate the boots effect. Tried jumping in an OTG generated world and received normal damage. Is there a workaround for this? I'm on 1.12.2.

**Comment by xbony2** [comment]
I don't have any plans to return to 1.12 rn, also very unclear why this bug is a thing. Issue is open for those who are interested.

**Comment by xbony2** [comment]
I believe this bug should be resolved but I don't really know for sure. Unfortunately I will not be returning to 1.12, but Long Fall Boots for 1.15 and 1.16 should be safe.
